import { usePage } from '@inertiajs/vue3';
import { createCampPlaybookEditorCore } from './useCampPlaybookEditor.core';
import { createCampPlaybookEditorOperations } from './useCampPlaybookEditor.operations';

export function useCampPlaybookEditor(props) {
    const page = usePage();
    const core = createCampPlaybookEditorCore(props, page);
    const operations = createCampPlaybookEditorOperations(props, core);

    return {
        canUpdate: core.canUpdate,
        isEdit: core.isEdit,
        speltakLabel: core.speltakLabel,
        form: core.form,
        coverPreviewUrl: core.coverPreviewUrl,
        isFramCamp: core.isFramCamp,
        corveeVinOptions: core.corveeVinOptions,
        vinHeaderValues: core.vinHeaderValues,
        activeSectionIndex: core.activeSectionIndex,
        activeSection: core.activeSection,
        deleteModalOpen: core.deleteModalOpen,
        submit: operations.submit,
        destroyItem: operations.destroyItem,
        openDeleteModal: operations.openDeleteModal,
        closeDeleteModal: operations.closeDeleteModal,
        statusLabel: core.statusLabel,
        statusClass: core.statusClass,
        setCampLocation: operations.setCampLocation,
        onCoverPhotoSelected: operations.onCoverPhotoSelected,
        removeCoverPhoto: operations.removeCoverPhoto,
        isAlgemeenSection: core.isAlgemeenSection,
        isHulpdienstenSection: core.isHulpdienstenSection,
        isTaakverdelingSection: core.isTaakverdelingSection,
        isTaakUitlegSection: core.isTaakUitlegSection,
        isAlgemeneAfsprakenSection: core.isAlgemeneAfsprakenSection,
        isSpeltakAfsprakenSection: core.isSpeltakAfsprakenSection,
        isCorveeroosterSection: core.isCorveeroosterSection,
        isVinindelingSection: core.isVinindelingSection,
        isMonsterrolSection: core.isMonsterrolSection,
        isPlanningPerDagSection: core.isPlanningPerDagSection,
        isVaarschemaSection: core.isVaarschemaSection,
        isStructuredSection: core.isStructuredSection,
        addPlanningDay: operations.addPlanningDay,
        removePlanningDay: operations.removePlanningDay,
        addPlanningRow: operations.addPlanningRow,
        removePlanningRow: operations.removePlanningRow,
        autosizeTextarea: operations.autosizeTextarea,
        startPlanningRowDrag: operations.startPlanningRowDrag,
        allowPlanningRowDrop: operations.allowPlanningRowDrop,
        dropPlanningRow: operations.dropPlanningRow,
        endPlanningRowDrag: operations.endPlanningRowDrag,
        normalizedDaywatchIds: operations.normalizedDaywatchIds,
        daywatchNameById: operations.daywatchNameById,
        availableDaywatchOptions: operations.availableDaywatchOptions,
        addDaywatchFromSelect: operations.addDaywatchFromSelect,
        removeDaywatch: operations.removeDaywatch,
        addVaarschemaRow: operations.addVaarschemaRow,
        removeVaarschemaRow: operations.removeVaarschemaRow,
        addMonsterrolRow: operations.addMonsterrolRow,
        removeMonsterrolRow: operations.removeMonsterrolRow,
        normalizeResponsibleNames: core.normalizeResponsibleNames,
        isDagverloopTask: operations.isDagverloopTask,
        availableResponsibleOptions: operations.availableResponsibleOptions,
        addResponsibleToTask: operations.addResponsibleToTask,
        removeResponsibleFromTask: operations.removeResponsibleFromTask,
        addTaskExplanationItem: operations.addTaskExplanationItem,
        removeTaskExplanationItem: operations.removeTaskExplanationItem,
        addTaskBullet: operations.addTaskBullet,
        removeTaskBullet: operations.removeTaskBullet,
        addGeneralAgreementItem: operations.addGeneralAgreementItem,
        removeGeneralAgreementItem: operations.removeGeneralAgreementItem,
        addGeneralAgreementBullet: operations.addGeneralAgreementBullet,
        removeGeneralAgreementBullet: operations.removeGeneralAgreementBullet,
        addSpeltakAgreementItem: operations.addSpeltakAgreementItem,
        removeSpeltakAgreementItem: operations.removeSpeltakAgreementItem,
        addSpeltakAgreementBullet: operations.addSpeltakAgreementBullet,
        removeSpeltakAgreementBullet: operations.removeSpeltakAgreementBullet,
        addSpeltakHygieneRow: operations.addSpeltakHygieneRow,
        removeSpeltakHygieneRow: operations.removeSpeltakHygieneRow,
        addVinindelingRow: operations.addVinindelingRow,
        removeVinindelingRow: operations.removeVinindelingRow,
        updateVinHeader: operations.updateVinHeader,
        vinCellSelection: operations.vinCellSelection,
        availableVinCellOptions: operations.availableVinCellOptions,
        setVinCellSelection: operations.setVinCellSelection,
        normalizeWholeMinutes: core.normalizeWholeMinutes,
        addCorveeRow: operations.addCorveeRow,
        removeCorveeRow: operations.removeCorveeRow,
        addEmergencyContactRow: operations.addEmergencyContactRow,
        removeEmergencyContactRow: operations.removeEmergencyContactRow,
    };
}
